# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e88960de13500b301372de2791779950c6738425ef9a47394c7d84014e9fc14b58af1b488208f049c1ed4585011c159e61d74ed65c1d82ca39e76f54e8d66fa

test:
  secret_key_base: c83fd3fcbeea09d00c36f27595446f77036b19533860ed14404966a274e81ee2331552a036e1f385e4b9b235f0de965ed1cc29585276172d4ee10dd8c03b6bf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
